### ISSUE TITLE
Scrape Greens candidate information

### ISSUE THREAD

**Issue by henare** [pat/my_candidates#1]
http://greens.org.au/candidates/all has all the candidates with links to pages with more information... unfortunately they're not in a standard format :cry: 

Could we do something dumb like search the page for the first Twitter link and just use that (for Twitter, for example)?

**Comment by pat** [comment]
I did scrape my Greens data from that list (well, state-focused versions of it - I didn't know there was a single page!) but it's certainly a shame that they didn't have social links in the summary (unlike both Coalition parties). Will look into some semi-intelligent scraper that gets Twitter/Facebook links, and maybe uses the candidate links from that initial page as their webpages.

**Comment by pat** [comment]
Okay, Greens data is vastly improved (though certainly there's many candidates without their own Facebook or Twitter pages). Separate state/territory pages actually have more people, so I stuck with those, and in the case of NT and ACT I manually added them to the page (as they're not in the common format).
