### ISSUE TITLE
Scrape ALP candidates details

### ISSUE THREAD

**Issue by henare** [pat/my_candidates#3]
http://www.alp.org.au/people/ the candidates and current members are mixed together and I don't know how to tell what members are going to be candidates again this election.

**Comment by pat** [comment]
That was my source as well. I scraped all MPs and candidates, and manually removed the duplicates by hand (e.g. Fremantle, Wills).

**Comment by henare** [comment]
Started this here https://morph.io/henare/2016_federal_election_alp_candidates still needs a bit of work.

**Comment by pat** [comment]
Presuming you're still working on this, but if at any point you want me to take a look, let me know!

**Comment by henare** [comment]
@pat I'm leaving the country tomorrow so I won't have time to come back to this for a while. If I do I'll comment here again.

**Comment by pat** [comment]
Sorted with the scraper in 299c0be7918415ec508de329edbc3e434cf0a3b0. Enjoy your trip! :)

**Comment by henare** [comment]
So good :ok_hand:
