### ISSUE TITLE
Add links to incumbent's OA.org and TVFY pages

### ISSUE THREAD

**Issue by henare** [pat/my_candidates#4]
From a suggestion by @pjf [on Twitter](https://twitter.com/pjf/status/729582625560494080), e.g.
- http://www.openaustralia.org.au/mp/malcolm_turnbull/wentworth
- https://theyvoteforyou.org.au/people/representatives/wentworth/malcolm_turnbull

**Comment by pat** [comment]
Done :) Also, new (but still simple) design, and a dedicated domain. http://votingchoices.com

**Comment by pjf** [comment]
You rock!

I'm also promoting votingchoices like a boss right now. :)

**Comment by pat** [comment]
Thanks Paul! Great to know you like the project, and the promotion is greatly appreciated :)
